### ISSUE TITLE
Use Cases document not linked

### ISSUE THREAD

**Issue by j08lue** [EOEPCA/system-architecture#2]
There is a document reference ([AD01](https://eoepca.readthedocs.io/projects/architecture/en/latest/document-references/#ad01)) for the use cases document, but it does not link to anything. 

https://github.com/EOEPCA/system-architecture/blob/02d6d931e4b104964563d7031c52a72d5a556244/docs/document-references.md?plain=1#L5-L7

![image](https://github.com/EOEPCA/system-architecture/assets/3404817/5dffe1b4-1517-45f6-a95f-19f43df83b41)

**Comment by rconway** [comment]
Thanks. Will take a look.

**Comment by rconway** [comment]
The Use Case doc (PDF) has been added as a `file` asset, and included as a hyperlink.
Applied to `latest` version and merged to `devel`.
